# Generated by Django 5.2.5 on 2025-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_like_mention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do post (PNG, JPEG, JPG, GIF)', null=True, upload_to='posts/images/'),
        ),
    ]
