# Generated by Django 5.2.5 on 2025-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, help_text='URL da imagem do post (Cloudinary)', max_length=500, null=True),
        ),
    ]
